generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Post
    theme:            default
    fields:
     texto: { params: rich=true tinymce_options=height:150 }    
    edit:
      title: Nueva entrada
      display: [texto]
