dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=rasengan_sucasports;host=localhost
      username:   rasengan_sucas
      password:   SSspJ6Jm
      encoding:   utf8
      persistent: true
      pooling:    true
