generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      FechaEtapaCarrera
    theme:            default
    list:
      title: Fechas para etapas de carrera
      display: [carrera_nombre,etap_nombre,fecha_inicio,fecha_fin,costo,max_corredores]
    edit:
      title: Agregar Fecha para esta carrera
      actions:
        _list:
        _save:
      display: [ _fecha_inicio_id, max_corredores, fecha_fin, costo ]
      fields:
        fecha_inicio_id: { name: fecha_inicio }