<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/10/09 22:17:46


$this->setDatabase('propel', new sfPropelDatabase(array (
  'dsn' => 'mysql://sucasports:9E63XUNu5@localhost/suca_sports',
  'name' => 'propel',
)));
