<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2008/10/09 22:17:50
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
