generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Post
    theme:            default
    edit:
      title: Nueva entrada
      display: [texto]
      layout:  stacked      
      max_per_page: 4
      filters: [post]