default:
  http_metas:
    content-type: text/html

  metas:
    title:        Portal de la aventura, run, MTB y triatlon en Uruguay
    #description:  symfony project
    keywords:     [uruguay,aventura,run, atletismo, maraton,cronometraje,suca,deporte,turismo,remo,d48,columbia]
    #language:     en
    robots:       index, follow

  stylesheets:    [main, dojo, dijit, soria/soria]

  javascripts:
    dojo:
      dojo/dojo/dojo:  { djConfig: 'parseOnLoad: false', isDebug: 'true' }
    dijit:      dojo/dijit/dijit.js
    dijit-all:  
      dojo/dijit/dijit-all.js: { charset: utf-8 }
    main:       main

  has_layout:     on
  layout:         layout
