default:
  http_metas:
    content-type: text/html

  metas:
    title:        SucaSports CMS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main, nihilo/nihilo, dojo]

  javascripts:
    dojo:
      dojo/dojo/dojo:  { djConfig: parseOnLoad:true, isDebug: true }
    prototype:    prototype


  has_layout:     on
  layout:         layout
