generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Carrera
    theme:            default
    edit :
      title: Editor de carreras
      display: [nombre,url,descripcion,categoria_carrera]
      fields:
        categoria_carrera: { type: admin_double_list, params: through_class=CategoriaCarrera }