default:
  http_metas:
    content-type: text/html

  metas:
    title:        SucaSports CMS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:
    main:       main


  has_layout:     on
  layout:         layoutcarrera

  components:
    sidebar:      [menu, inicio]
    context:      [menu, context]
    