SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `suca_sports`.`usuario` ADD COLUMN `email` VARCHAR(45) NULL DEFAULT NULL  AFTER `nombre`;
ALTER TABLE `suca_sports`.`usuario` ADD COLUMN `pregunta_secreta` VARCHAR(45) NULL DEFAULT NULL  AFTER `id_corredor`;
ALTER TABLE `suca_sports`.`usuario` ADD COLUMN `respuesta_secreta` VARCHAR(45) NULL DEFAULT NULL  AFTER `pregunta_secreta`;
ALTER TABLE `suca_sports`.`usuario` CHANGE COLUMN `nombre` `documento` VARCHAR(45) NULL DEFAULT NULL  ;
ALTER TABLE `suca_sports`.`usuario` ADD COLUMN `estado` CHAR(1) NULL DEFAULT NULL  AFTER `id_corredor`;
ALTER TABLE `suca_sports`.`usuario` ADD COLUMN `verificador` VARCHAR(255) NULL DEFAULT NULL AFTER `estado`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;