generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Carrera
    theme:            default
    edit :
      title: Editor de carreras
      actions:
        _list:
        _save:
        _delete:
        add_etapa:
          name: Agregar Etapa
          action: etapa
      display: [nombre,url,descripcion,categoria_carrera,_etapas,etapa_carrera]
      fields:
        categoria_carrera: { type: admin_double_list, params: through_class=CategoriaCarrera }