propel:
  _attributes:
    package: lib.model
  alquileres:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_equipamiento: { type: INTEGER, required: true, foreignTable: inventario, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_fecha_carrera: { type: INTEGER, foreignTable: fecha_etapa_carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_alquileres_equipamiento_id: [id_equipamiento], fk_alquileres_fecha_carrera_id: [id_fecha_carrera] }
  asociacion:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  asociacion_corredor:
    id_asociacion: { type: INTEGER, required: true, primaryKey: true, foreignTable: asociacion, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_corredor: { type: INTEGER, required: true, primaryKey: true, foreignTable: corredor, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_asociacion_has_corredor_asociacion: [id_asociacion], fk_asociacion_has_corredor_corredor: [id_corredor] }
  carrera:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
    url: { type: VARCHAR, size: '45' }
  categoria:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  categoria_carrera:
    id_categoria: { type: INTEGER, required: true, primaryKey: true, foreignTable: categoria, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_carrera: { type: INTEGER, foreignTable: carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_categoria_carrera_id_categoria: [id_categoria], fk_categoria_carrera_carrera: [id_carrera] }
  chips:
    id: { type: INTEGER, required: true, primaryKey: true }
    codigo_chip: { type: VARCHAR, size: '45' }
  corredor:
    id: { type: INTEGER, required: true, primaryKey: true }
    tipo_documento: { type: INTEGER }
    nombre: { type: VARCHAR, size: '45' }
    apellido: { type: VARCHAR, size: '45' }
    telefono: { type: VARCHAR, size: '45' }
    movil: { type: VARCHAR, size: '45' }
    telefono_emergencia: { type: VARCHAR, size: '45' }
    direccion: { type: VARCHAR, size: '45' }
    fecha_nacimiento: { type: DATE }
    pareja: { type: VARCHAR, size: '45' }
    hijos: { type: VARCHAR, size: '45' }
    id_sociedad_medica: { type: INTEGER, foreignTable: sociedad_medica, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    historia_medica: { type: VARCHAR, size: '255' }
    sexo: { type: VARCHAR, size: '1' }
    id_localidad: { type: INTEGER, foreignTable: localidad, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_pais: { type: INTEGER, foreignTable: pais, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_chips: { type: INTEGER, foreignTable: chips, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_usuario: { type: INTEGER, required: true, primaryKey: true, foreignTable: usuarios, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_corredor_id_sociedad_medida: [id_sociedad_medica], fk_corredor_id_pais: [id_pais], fk_corredor_id_localidad: [id_localidad], fk_corredor_chips: [id_chips], fk_corredor_usuarios: [id_usuario] }
  corredor_equipamiento:
    id_corredor: { type: INTEGER, required: true, primaryKey: true, foreignTable: corredor, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_equipamiento: { type: INTEGER, required: true, primaryKey: true, foreignTable: equipamiento, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_corredor_has_equipamiento_corredor: [id_corredor], fk_corredor_has_equipamiento_equipamiento: [id_equipamiento] }
  cuenta_corriente:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_corredor: { type: INTEGER, foreignTable: corredor, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_forma_pago: { type: INTEGER, foreignTable: forma_pago, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    monto: { type: DOUBLE }
    _indexes: { fk_cuenta_corriente_id_corredor: [id_corredor], fk_cuenta_corriente_id_forma_pago: [id_forma_pago] }
  equipamiento:
    id: { type: INTEGER, required: true, primaryKey: true }
    marca: { type: VARCHAR, size: '45' }
    id_tipo_equipamiento: { type: INTEGER, foreignTable: tipo_equipamiento, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_equipamiento_tipo_equipamiento: [id_tipo_equipamiento] }
  equipamiento_carrera:
    id_carrera: { type: INTEGER, required: true, primaryKey: true, foreignTable: fecha_etapa_carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_tipo_equipamiento: { type: INTEGER, foreignTable: tipo_equipamiento, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_equipamiento_carrera_id_carrera: [id_carrera], fk_equipamiento_carrera_tipo_equipamiento: [id_tipo_equipamiento] }
  etapa_carrera:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
    numero_etapa: { type: INTEGER }
    id_etapa: { type: INTEGER, foreignTable: carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_etapa_carrera_etapa: [id_etapa] }
  fecha_etapa_carrera:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_carrera: { type: INTEGER, foreignTable: etapa_carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    max_corredores: { type: INTEGER }
    fecha_inicio: { type: DATE }
    fecha_fin: { type: DATE }
    _indexes: { fk_fecha_carrera_id_carrera: [id_carrera] }
  forma_pago:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  grupos:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  inscripcion:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_carrera: { type: INTEGER, required: true, foreignTable: fecha_etapa_carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_corredor: { type: INTEGER, required: true, foreignTable: corredor, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_inscripcion_id_carrera: [id_carrera], fk_inscripcion_id_corredor: [id_corredor] }
  inventario:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
    id_tipo_equipamiento: { type: INTEGER, foreignTable: equipamiento, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_inventario_tipo_equipamiento: [id_tipo_equipamiento] }
  localidad:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_pais: { type: INTEGER, foreignTable: pais, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    nombre: { type: VARCHAR, size: '45' }
    _indexes: { fk_localidad_id_pais: [id_pais] }
  pais:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  post:
    id: { type: INTEGER, required: true, primaryKey: true }
    texto: { type: LONGVARCHAR }
    id_usuarios: { type: INTEGER, foreignTable: usuarios, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_post_usuarios: [id_usuarios] }
  resultados:
    id: { type: INTEGER, required: true, primaryKey: true }
    id_fecha_carrera: { type: INTEGER, foreignTable: fecha_etapa_carrera, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_resultados_fecha_carrera: [id_fecha_carrera] }
  sociedad_medica:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
  tipo_equipamiento:
    id: { type: INTEGER, required: true, primaryKey: true }
    tipo: { type: VARCHAR, size: '45' }
  usuarios:
    id: { type: INTEGER, required: true, primaryKey: true }
    nombre: { type: VARCHAR, size: '45' }
    id_grupos: { type: INTEGER, foreignTable: grupos, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { fk_usuarios_grupos: [id_grupos] }
