generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Post
    theme:            default
    list:
      title: Entradas Carreras
      display: [=texto, updated_at, updated_by]
      filters: [texto, updated_at, updated_by]         
    edit:
      title: Editar entrada
      display: [texto, fecha_etapa_carrera_fecha_inicio ]
