<?php

/**
 * Base class that represents a row from the 'cuenta_corriente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 02/04/09 01:14:04
 *
 * @package    lib.model.om
 */
abstract class BaseCuentaCorriente extends BaseObject  implements Persistent {


  const PEER = 'CuentaCorrientePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CuentaCorrientePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the id_corredor field.
	 * @var        int
	 */
	protected $id_corredor;

	/**
	 * The value for the id_forma_pago field.
	 * @var        int
	 */
	protected $id_forma_pago;

	/**
	 * The value for the monto field.
	 * @var        double
	 */
	protected $monto;

	/**
	 * The value for the concepto field.
	 * @var        string
	 */
	protected $concepto;

	/**
	 * The value for the firma_digital field.
	 * @var        string
	 */
	protected $firma_digital;

	/**
	 * The value for the fecha_de_pago field.
	 * @var        string
	 */
	protected $fecha_de_pago;

	/**
	 * The value for the nota field.
	 * @var        string
	 */
	protected $nota;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the created_by field.
	 * @var        int
	 */
	protected $created_by;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the updated_by field.
	 * @var        int
	 */
	protected $updated_by;

	/**
	 * @var        Corredor
	 */
	protected $aCorredor;

	/**
	 * @var        FormaPago
	 */
	protected $aFormaPago;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCuentaCorriente object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [id_corredor] column value.
	 * 
	 * @return     int
	 */
	public function getIdCorredor()
	{
		return $this->id_corredor;
	}

	/**
	 * Get the [id_forma_pago] column value.
	 * 
	 * @return     int
	 */
	public function getIdFormaPago()
	{
		return $this->id_forma_pago;
	}

	/**
	 * Get the [monto] column value.
	 * 
	 * @return     double
	 */
	public function getMonto()
	{
		return $this->monto;
	}

	/**
	 * Get the [concepto] column value.
	 * 
	 * @return     string
	 */
	public function getConcepto()
	{
		return $this->concepto;
	}

	/**
	 * Get the [firma_digital] column value.
	 * 
	 * @return     string
	 */
	public function getFirmaDigital()
	{
		return $this->firma_digital;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_de_pago] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaDePago($format = 'Y-m-d')
	{
		if ($this->fecha_de_pago === null) {
			return null;
		}


		if ($this->fecha_de_pago === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_de_pago);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_de_pago, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [nota] column value.
	 * 
	 * @return     string
	 */
	public function getNota()
	{
		return $this->nota;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by] column value.
	 * 
	 * @return     int
	 */
	public function getCreatedBy()
	{
		return $this->created_by;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [updated_by] column value.
	 * 
	 * @return     int
	 */
	public function getUpdatedBy()
	{
		return $this->updated_by;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [id_corredor] column.
	 * 
	 * @param      int $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setIdCorredor($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_corredor !== $v) {
			$this->id_corredor = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::ID_CORREDOR;
		}

		if ($this->aCorredor !== null && $this->aCorredor->getId() !== $v) {
			$this->aCorredor = null;
		}

		return $this;
	} // setIdCorredor()

	/**
	 * Set the value of [id_forma_pago] column.
	 * 
	 * @param      int $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setIdFormaPago($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_forma_pago !== $v) {
			$this->id_forma_pago = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::ID_FORMA_PAGO;
		}

		if ($this->aFormaPago !== null && $this->aFormaPago->getId() !== $v) {
			$this->aFormaPago = null;
		}

		return $this;
	} // setIdFormaPago()

	/**
	 * Set the value of [monto] column.
	 * 
	 * @param      double $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setMonto($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->monto !== $v) {
			$this->monto = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::MONTO;
		}

		return $this;
	} // setMonto()

	/**
	 * Set the value of [concepto] column.
	 * 
	 * @param      string $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setConcepto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->concepto !== $v) {
			$this->concepto = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::CONCEPTO;
		}

		return $this;
	} // setConcepto()

	/**
	 * Set the value of [firma_digital] column.
	 * 
	 * @param      string $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setFirmaDigital($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->firma_digital !== $v) {
			$this->firma_digital = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::FIRMA_DIGITAL;
		}

		return $this;
	} // setFirmaDigital()

	/**
	 * Sets the value of [fecha_de_pago] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setFechaDePago($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_de_pago !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_de_pago !== null && $tmpDt = new DateTime($this->fecha_de_pago)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_de_pago = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CuentaCorrientePeer::FECHA_DE_PAGO;
			}
		} // if either are not null

		return $this;
	} // setFechaDePago()

	/**
	 * Set the value of [nota] column.
	 * 
	 * @param      string $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setNota($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nota !== $v) {
			$this->nota = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::NOTA;
		}

		return $this;
	} // setNota()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CuentaCorrientePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [created_by] column.
	 * 
	 * @param      int $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setCreatedBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->created_by !== $v) {
			$this->created_by = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::CREATED_BY;
		}

		return $this;
	} // setCreatedBy()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CuentaCorrientePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [updated_by] column.
	 * 
	 * @param      int $v new value
	 * @return     CuentaCorriente The current object (for fluent API support)
	 */
	public function setUpdatedBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->updated_by !== $v) {
			$this->updated_by = $v;
			$this->modifiedColumns[] = CuentaCorrientePeer::UPDATED_BY;
		}

		return $this;
	} // setUpdatedBy()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_corredor = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->id_forma_pago = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->monto = ($row[$startcol + 3] !== null) ? (double) $row[$startcol + 3] : null;
			$this->concepto = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->firma_digital = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fecha_de_pago = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->nota = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->created_by = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->updated_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->updated_by = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = CuentaCorrientePeer::NUM_COLUMNS - CuentaCorrientePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating CuentaCorriente object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCorredor !== null && $this->id_corredor !== $this->aCorredor->getId()) {
			$this->aCorredor = null;
		}
		if ($this->aFormaPago !== null && $this->id_forma_pago !== $this->aFormaPago->getId()) {
			$this->aFormaPago = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CuentaCorrientePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CuentaCorrientePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCorredor = null;
			$this->aFormaPago = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCuentaCorriente:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CuentaCorrientePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CuentaCorrientePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCuentaCorriente:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCuentaCorriente:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(CuentaCorrientePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(CuentaCorrientePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CuentaCorrientePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCuentaCorriente:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CuentaCorrientePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCorredor !== null) {
				if ($this->aCorredor->isModified() || $this->aCorredor->isNew()) {
					$affectedRows += $this->aCorredor->save($con);
				}
				$this->setCorredor($this->aCorredor);
			}

			if ($this->aFormaPago !== null) {
				if ($this->aFormaPago->isModified() || $this->aFormaPago->isNew()) {
					$affectedRows += $this->aFormaPago->save($con);
				}
				$this->setFormaPago($this->aFormaPago);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CuentaCorrientePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CuentaCorrientePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CuentaCorrientePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCorredor !== null) {
				if (!$this->aCorredor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCorredor->getValidationFailures());
				}
			}

			if ($this->aFormaPago !== null) {
				if (!$this->aFormaPago->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFormaPago->getValidationFailures());
				}
			}


			if (($retval = CuentaCorrientePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CuentaCorrientePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIdCorredor();
				break;
			case 2:
				return $this->getIdFormaPago();
				break;
			case 3:
				return $this->getMonto();
				break;
			case 4:
				return $this->getConcepto();
				break;
			case 5:
				return $this->getFirmaDigital();
				break;
			case 6:
				return $this->getFechaDePago();
				break;
			case 7:
				return $this->getNota();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getCreatedBy();
				break;
			case 10:
				return $this->getUpdatedAt();
				break;
			case 11:
				return $this->getUpdatedBy();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CuentaCorrientePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIdCorredor(),
			$keys[2] => $this->getIdFormaPago(),
			$keys[3] => $this->getMonto(),
			$keys[4] => $this->getConcepto(),
			$keys[5] => $this->getFirmaDigital(),
			$keys[6] => $this->getFechaDePago(),
			$keys[7] => $this->getNota(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getCreatedBy(),
			$keys[10] => $this->getUpdatedAt(),
			$keys[11] => $this->getUpdatedBy(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CuentaCorrientePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIdCorredor($value);
				break;
			case 2:
				$this->setIdFormaPago($value);
				break;
			case 3:
				$this->setMonto($value);
				break;
			case 4:
				$this->setConcepto($value);
				break;
			case 5:
				$this->setFirmaDigital($value);
				break;
			case 6:
				$this->setFechaDePago($value);
				break;
			case 7:
				$this->setNota($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setCreatedBy($value);
				break;
			case 10:
				$this->setUpdatedAt($value);
				break;
			case 11:
				$this->setUpdatedBy($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CuentaCorrientePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdCorredor($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdFormaPago($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setMonto($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setConcepto($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFirmaDigital($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFechaDePago($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNota($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedBy($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUpdatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUpdatedBy($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CuentaCorrientePeer::DATABASE_NAME);

		if ($this->isColumnModified(CuentaCorrientePeer::ID)) $criteria->add(CuentaCorrientePeer::ID, $this->id);
		if ($this->isColumnModified(CuentaCorrientePeer::ID_CORREDOR)) $criteria->add(CuentaCorrientePeer::ID_CORREDOR, $this->id_corredor);
		if ($this->isColumnModified(CuentaCorrientePeer::ID_FORMA_PAGO)) $criteria->add(CuentaCorrientePeer::ID_FORMA_PAGO, $this->id_forma_pago);
		if ($this->isColumnModified(CuentaCorrientePeer::MONTO)) $criteria->add(CuentaCorrientePeer::MONTO, $this->monto);
		if ($this->isColumnModified(CuentaCorrientePeer::CONCEPTO)) $criteria->add(CuentaCorrientePeer::CONCEPTO, $this->concepto);
		if ($this->isColumnModified(CuentaCorrientePeer::FIRMA_DIGITAL)) $criteria->add(CuentaCorrientePeer::FIRMA_DIGITAL, $this->firma_digital);
		if ($this->isColumnModified(CuentaCorrientePeer::FECHA_DE_PAGO)) $criteria->add(CuentaCorrientePeer::FECHA_DE_PAGO, $this->fecha_de_pago);
		if ($this->isColumnModified(CuentaCorrientePeer::NOTA)) $criteria->add(CuentaCorrientePeer::NOTA, $this->nota);
		if ($this->isColumnModified(CuentaCorrientePeer::CREATED_AT)) $criteria->add(CuentaCorrientePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(CuentaCorrientePeer::CREATED_BY)) $criteria->add(CuentaCorrientePeer::CREATED_BY, $this->created_by);
		if ($this->isColumnModified(CuentaCorrientePeer::UPDATED_AT)) $criteria->add(CuentaCorrientePeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(CuentaCorrientePeer::UPDATED_BY)) $criteria->add(CuentaCorrientePeer::UPDATED_BY, $this->updated_by);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CuentaCorrientePeer::DATABASE_NAME);

		$criteria->add(CuentaCorrientePeer::ID, $this->id);
		$criteria->add(CuentaCorrientePeer::ID_CORREDOR, $this->id_corredor);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getId();

		$pks[1] = $this->getIdCorredor();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setId($keys[0]);

		$this->setIdCorredor($keys[1]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of CuentaCorriente (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdCorredor($this->id_corredor);

		$copyObj->setIdFormaPago($this->id_forma_pago);

		$copyObj->setMonto($this->monto);

		$copyObj->setConcepto($this->concepto);

		$copyObj->setFirmaDigital($this->firma_digital);

		$copyObj->setFechaDePago($this->fecha_de_pago);

		$copyObj->setNota($this->nota);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setCreatedBy($this->created_by);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setUpdatedBy($this->updated_by);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     CuentaCorriente Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CuentaCorrientePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CuentaCorrientePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Corredor object.
	 *
	 * @param      Corredor $v
	 * @return     CuentaCorriente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCorredor(Corredor $v = null)
	{
		if ($v === null) {
			$this->setIdCorredor(NULL);
		} else {
			$this->setIdCorredor($v->getId());
		}

		$this->aCorredor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Corredor object, it will not be re-added.
		if ($v !== null) {
			$v->addCuentaCorriente($this);
		}

		return $this;
	}


	/**
	 * Get the associated Corredor object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Corredor The associated Corredor object.
	 * @throws     PropelException
	 */
	public function getCorredor(PropelPDO $con = null)
	{
		if ($this->aCorredor === null && ($this->id_corredor !== null)) {
			$c = new Criteria(CorredorPeer::DATABASE_NAME);
			$c->add(CorredorPeer::ID, $this->id_corredor);
			$this->aCorredor = CorredorPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCorredor->addCuentaCorrientes($this);
			 */
		}
		return $this->aCorredor;
	}

	/**
	 * Declares an association between this object and a FormaPago object.
	 *
	 * @param      FormaPago $v
	 * @return     CuentaCorriente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFormaPago(FormaPago $v = null)
	{
		if ($v === null) {
			$this->setIdFormaPago(NULL);
		} else {
			$this->setIdFormaPago($v->getId());
		}

		$this->aFormaPago = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the FormaPago object, it will not be re-added.
		if ($v !== null) {
			$v->addCuentaCorriente($this);
		}

		return $this;
	}


	/**
	 * Get the associated FormaPago object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     FormaPago The associated FormaPago object.
	 * @throws     PropelException
	 */
	public function getFormaPago(PropelPDO $con = null)
	{
		if ($this->aFormaPago === null && ($this->id_forma_pago !== null)) {
			$c = new Criteria(FormaPagoPeer::DATABASE_NAME);
			$c->add(FormaPagoPeer::ID, $this->id_forma_pago);
			$this->aFormaPago = FormaPagoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFormaPago->addCuentaCorrientes($this);
			 */
		}
		return $this->aFormaPago;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCorredor = null;
			$this->aFormaPago = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCuentaCorriente:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCuentaCorriente::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCuentaCorriente
