<?php

/**
 * Base static class for performing query and update operations on the 'fecha_etapa_carrera' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 02/04/09 01:14:04
 *
 * @package    lib.model.om
 */
abstract class BaseFechaEtapaCarreraPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'fecha_etapa_carrera';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.FechaEtapaCarrera';

	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the FECHA_INICIO field */
	const FECHA_INICIO = 'fecha_etapa_carrera.FECHA_INICIO';

	/** the column name for the ID_ETAPA field */
	const ID_ETAPA = 'fecha_etapa_carrera.ID_ETAPA';

	/** the column name for the ID_CARRERA field */
	const ID_CARRERA = 'fecha_etapa_carrera.ID_CARRERA';

	/** the column name for the MAX_CORREDORES field */
	const MAX_CORREDORES = 'fecha_etapa_carrera.MAX_CORREDORES';

	/** the column name for the FECHA_FIN field */
	const FECHA_FIN = 'fecha_etapa_carrera.FECHA_FIN';

	/** the column name for the COSTO field */
	const COSTO = 'fecha_etapa_carrera.COSTO';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'fecha_etapa_carrera.CREATED_AT';

	/** the column name for the CREATED_BY field */
	const CREATED_BY = 'fecha_etapa_carrera.CREATED_BY';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'fecha_etapa_carrera.UPDATED_AT';

	/** the column name for the UPDATED_BY field */
	const UPDATED_BY = 'fecha_etapa_carrera.UPDATED_BY';

	/** the column name for the ESTADO field */
	const ESTADO = 'fecha_etapa_carrera.ESTADO';

	/**
	 * An identiy map to hold any loaded instances of FechaEtapaCarrera objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array FechaEtapaCarrera[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('FechaInicio', 'IdEtapa', 'IdCarrera', 'MaxCorredores', 'FechaFin', 'Costo', 'CreatedAt', 'CreatedBy', 'UpdatedAt', 'UpdatedBy', 'Estado', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('fechaInicio', 'idEtapa', 'idCarrera', 'maxCorredores', 'fechaFin', 'costo', 'createdAt', 'createdBy', 'updatedAt', 'updatedBy', 'estado', ),
		BasePeer::TYPE_COLNAME => array (self::FECHA_INICIO, self::ID_ETAPA, self::ID_CARRERA, self::MAX_CORREDORES, self::FECHA_FIN, self::COSTO, self::CREATED_AT, self::CREATED_BY, self::UPDATED_AT, self::UPDATED_BY, self::ESTADO, ),
		BasePeer::TYPE_FIELDNAME => array ('fecha_inicio', 'id_etapa', 'id_carrera', 'max_corredores', 'fecha_fin', 'costo', 'created_at', 'created_by', 'updated_at', 'updated_by', 'estado', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('FechaInicio' => 0, 'IdEtapa' => 1, 'IdCarrera' => 2, 'MaxCorredores' => 3, 'FechaFin' => 4, 'Costo' => 5, 'CreatedAt' => 6, 'CreatedBy' => 7, 'UpdatedAt' => 8, 'UpdatedBy' => 9, 'Estado' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('fechaInicio' => 0, 'idEtapa' => 1, 'idCarrera' => 2, 'maxCorredores' => 3, 'fechaFin' => 4, 'costo' => 5, 'createdAt' => 6, 'createdBy' => 7, 'updatedAt' => 8, 'updatedBy' => 9, 'estado' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::FECHA_INICIO => 0, self::ID_ETAPA => 1, self::ID_CARRERA => 2, self::MAX_CORREDORES => 3, self::FECHA_FIN => 4, self::COSTO => 5, self::CREATED_AT => 6, self::CREATED_BY => 7, self::UPDATED_AT => 8, self::UPDATED_BY => 9, self::ESTADO => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('fecha_inicio' => 0, 'id_etapa' => 1, 'id_carrera' => 2, 'max_corredores' => 3, 'fecha_fin' => 4, 'costo' => 5, 'created_at' => 6, 'created_by' => 7, 'updated_at' => 8, 'updated_by' => 9, 'estado' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new FechaEtapaCarreraMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. FechaEtapaCarreraPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(FechaEtapaCarreraPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::FECHA_INICIO);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::ID_ETAPA);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::ID_CARRERA);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::MAX_CORREDORES);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::FECHA_FIN);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::COSTO);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::CREATED_AT);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::CREATED_BY);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::UPDATED_AT);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::UPDATED_BY);

		$criteria->addSelectColumn(FechaEtapaCarreraPeer::ESTADO);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FechaEtapaCarreraPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FechaEtapaCarreraPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     FechaEtapaCarrera
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = FechaEtapaCarreraPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return FechaEtapaCarreraPeer::populateObjects(FechaEtapaCarreraPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			FechaEtapaCarreraPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      FechaEtapaCarrera $value A FechaEtapaCarrera object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(FechaEtapaCarrera $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = serialize(array((string) $obj->getFechaInicio(), (string) $obj->getIdEtapa(), (string) $obj->getIdCarrera()));
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A FechaEtapaCarrera object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof FechaEtapaCarrera) {
				$key = serialize(array((string) $value->getFechaInicio(), (string) $value->getIdEtapa(), (string) $value->getIdCarrera()));
			} elseif (is_array($value) && count($value) === 3) {
				// assume we've been passed a primary key
				$key = serialize(array((string) $value[0], (string) $value[1], (string) $value[2]));
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or FechaEtapaCarrera object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     FechaEtapaCarrera Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null && $row[$startcol + 1] === null && $row[$startcol + 2] === null) {
			return null;
		}
		return serialize(array((string) $row[$startcol + 0], (string) $row[$startcol + 1], (string) $row[$startcol + 2]));
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = FechaEtapaCarreraPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = FechaEtapaCarreraPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = FechaEtapaCarreraPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				FechaEtapaCarreraPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return FechaEtapaCarreraPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a FechaEtapaCarrera or Criteria object.
	 *
	 * @param      mixed $values Criteria or FechaEtapaCarrera object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from FechaEtapaCarrera object
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a FechaEtapaCarrera or Criteria object.
	 *
	 * @param      mixed $values Criteria or FechaEtapaCarrera object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(FechaEtapaCarreraPeer::FECHA_INICIO);
			$selectCriteria->add(FechaEtapaCarreraPeer::FECHA_INICIO, $criteria->remove(FechaEtapaCarreraPeer::FECHA_INICIO), $comparison);

			$comparison = $criteria->getComparison(FechaEtapaCarreraPeer::ID_ETAPA);
			$selectCriteria->add(FechaEtapaCarreraPeer::ID_ETAPA, $criteria->remove(FechaEtapaCarreraPeer::ID_ETAPA), $comparison);

			$comparison = $criteria->getComparison(FechaEtapaCarreraPeer::ID_CARRERA);
			$selectCriteria->add(FechaEtapaCarreraPeer::ID_CARRERA, $criteria->remove(FechaEtapaCarreraPeer::ID_CARRERA), $comparison);

		} else { // $values is FechaEtapaCarrera object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseFechaEtapaCarreraPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseFechaEtapaCarreraPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the fecha_etapa_carrera table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(FechaEtapaCarreraPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a FechaEtapaCarrera or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or FechaEtapaCarrera object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			FechaEtapaCarreraPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof FechaEtapaCarrera) {
			// invalidate the cache for this single object
			FechaEtapaCarreraPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			// primary key is composite; we therefore, expect
			// the primary key passed to be an array of pkey
			// values
			if (count($values) == count($values, COUNT_RECURSIVE)) {
				// array is not multi-dimensional
				$values = array($values);
			}

			foreach ($values as $value) {

				$criterion = $criteria->getNewCriterion(FechaEtapaCarreraPeer::FECHA_INICIO, $value[0]);
				$criterion->addAnd($criteria->getNewCriterion(FechaEtapaCarreraPeer::ID_ETAPA, $value[1]));
				$criterion->addAnd($criteria->getNewCriterion(FechaEtapaCarreraPeer::ID_CARRERA, $value[2]));
				$criteria->addOr($criterion);

				// we can invalidate the cache for this single PK
				FechaEtapaCarreraPeer::removeInstanceFromPool($value);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given FechaEtapaCarrera object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      FechaEtapaCarrera $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(FechaEtapaCarrera $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(FechaEtapaCarreraPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(FechaEtapaCarreraPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(FechaEtapaCarreraPeer::DATABASE_NAME, FechaEtapaCarreraPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = FechaEtapaCarreraPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve object using using composite pkey values.
	 * @param      string $fecha_inicio
	   @param      int $id_etapa
	   @param      int $id_carrera
	   
	 * @param      PropelPDO $con
	 * @return     FechaEtapaCarrera
	 */
	public static function retrieveByPK($fecha_inicio, $id_etapa, $id_carrera, PropelPDO $con = null) {
		$key = serialize(array((string) $fecha_inicio, (string) $id_etapa, (string) $id_carrera));
 		if (null !== ($obj = FechaEtapaCarreraPeer::getInstanceFromPool($key))) {
 			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(FechaEtapaCarreraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$criteria = new Criteria(FechaEtapaCarreraPeer::DATABASE_NAME);
		$criteria->add(FechaEtapaCarreraPeer::FECHA_INICIO, $fecha_inicio);
		$criteria->add(FechaEtapaCarreraPeer::ID_ETAPA, $id_etapa);
		$criteria->add(FechaEtapaCarreraPeer::ID_CARRERA, $id_carrera);
		$v = FechaEtapaCarreraPeer::doSelect($criteria, $con);

		return !empty($v) ? $v[0] : null;
	}
} // BaseFechaEtapaCarreraPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the FechaEtapaCarreraPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the FechaEtapaCarreraPeer class:
//
// Propel::getDatabaseMap(FechaEtapaCarreraPeer::DATABASE_NAME)->addTableBuilder(FechaEtapaCarreraPeer::TABLE_NAME, FechaEtapaCarreraPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseFechaEtapaCarreraPeer::DATABASE_NAME)->addTableBuilder(BaseFechaEtapaCarreraPeer::TABLE_NAME, BaseFechaEtapaCarreraPeer::getMapBuilder());

