<?php

/**
 * Base static class for performing query and update operations on the 'corredor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 02/04/09 01:14:04
 *
 * @package    lib.model.om
 */
abstract class BaseCorredorPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'corredor';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Corredor';

	/** The total number of columns. */
	const NUM_COLUMNS = 22;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'corredor.ID';

	/** the column name for the DOCUMENTO field */
	const DOCUMENTO = 'corredor.DOCUMENTO';

	/** the column name for the ID_TIPO_DOCUMENTO field */
	const ID_TIPO_DOCUMENTO = 'corredor.ID_TIPO_DOCUMENTO';

	/** the column name for the NOMBRE field */
	const NOMBRE = 'corredor.NOMBRE';

	/** the column name for the APELLIDO field */
	const APELLIDO = 'corredor.APELLIDO';

	/** the column name for the TELEFONO field */
	const TELEFONO = 'corredor.TELEFONO';

	/** the column name for the MOVIL field */
	const MOVIL = 'corredor.MOVIL';

	/** the column name for the TELEFONO_EMERGENCIA field */
	const TELEFONO_EMERGENCIA = 'corredor.TELEFONO_EMERGENCIA';

	/** the column name for the DIRECCION field */
	const DIRECCION = 'corredor.DIRECCION';

	/** the column name for the FECHA_NACIMIENTO field */
	const FECHA_NACIMIENTO = 'corredor.FECHA_NACIMIENTO';

	/** the column name for the PAREJA field */
	const PAREJA = 'corredor.PAREJA';

	/** the column name for the HIJOS field */
	const HIJOS = 'corredor.HIJOS';

	/** the column name for the ID_SOCIEDAD_MEDICA field */
	const ID_SOCIEDAD_MEDICA = 'corredor.ID_SOCIEDAD_MEDICA';

	/** the column name for the HISTORIA_MEDICA field */
	const HISTORIA_MEDICA = 'corredor.HISTORIA_MEDICA';

	/** the column name for the SEXO field */
	const SEXO = 'corredor.SEXO';

	/** the column name for the ID_LOCALIDAD field */
	const ID_LOCALIDAD = 'corredor.ID_LOCALIDAD';

	/** the column name for the ID_PAIS field */
	const ID_PAIS = 'corredor.ID_PAIS';

	/** the column name for the ID_CHIPS field */
	const ID_CHIPS = 'corredor.ID_CHIPS';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'corredor.UPDATED_AT';

	/** the column name for the UPDATED_BY field */
	const UPDATED_BY = 'corredor.UPDATED_BY';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'corredor.CREATED_AT';

	/** the column name for the CREATED_BY field */
	const CREATED_BY = 'corredor.CREATED_BY';

	/**
	 * An identiy map to hold any loaded instances of Corredor objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Corredor[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Documento', 'IdTipoDocumento', 'Nombre', 'Apellido', 'Telefono', 'Movil', 'TelefonoEmergencia', 'Direccion', 'FechaNacimiento', 'Pareja', 'Hijos', 'IdSociedadMedica', 'HistoriaMedica', 'Sexo', 'IdLocalidad', 'IdPais', 'IdChips', 'UpdatedAt', 'UpdatedBy', 'CreatedAt', 'CreatedBy', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'documento', 'idTipoDocumento', 'nombre', 'apellido', 'telefono', 'movil', 'telefonoEmergencia', 'direccion', 'fechaNacimiento', 'pareja', 'hijos', 'idSociedadMedica', 'historiaMedica', 'sexo', 'idLocalidad', 'idPais', 'idChips', 'updatedAt', 'updatedBy', 'createdAt', 'createdBy', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::DOCUMENTO, self::ID_TIPO_DOCUMENTO, self::NOMBRE, self::APELLIDO, self::TELEFONO, self::MOVIL, self::TELEFONO_EMERGENCIA, self::DIRECCION, self::FECHA_NACIMIENTO, self::PAREJA, self::HIJOS, self::ID_SOCIEDAD_MEDICA, self::HISTORIA_MEDICA, self::SEXO, self::ID_LOCALIDAD, self::ID_PAIS, self::ID_CHIPS, self::UPDATED_AT, self::UPDATED_BY, self::CREATED_AT, self::CREATED_BY, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'documento', 'id_tipo_documento', 'nombre', 'apellido', 'telefono', 'movil', 'telefono_emergencia', 'direccion', 'fecha_nacimiento', 'pareja', 'hijos', 'id_sociedad_medica', 'historia_medica', 'sexo', 'id_localidad', 'id_pais', 'id_chips', 'updated_at', 'updated_by', 'created_at', 'created_by', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Documento' => 1, 'IdTipoDocumento' => 2, 'Nombre' => 3, 'Apellido' => 4, 'Telefono' => 5, 'Movil' => 6, 'TelefonoEmergencia' => 7, 'Direccion' => 8, 'FechaNacimiento' => 9, 'Pareja' => 10, 'Hijos' => 11, 'IdSociedadMedica' => 12, 'HistoriaMedica' => 13, 'Sexo' => 14, 'IdLocalidad' => 15, 'IdPais' => 16, 'IdChips' => 17, 'UpdatedAt' => 18, 'UpdatedBy' => 19, 'CreatedAt' => 20, 'CreatedBy' => 21, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'documento' => 1, 'idTipoDocumento' => 2, 'nombre' => 3, 'apellido' => 4, 'telefono' => 5, 'movil' => 6, 'telefonoEmergencia' => 7, 'direccion' => 8, 'fechaNacimiento' => 9, 'pareja' => 10, 'hijos' => 11, 'idSociedadMedica' => 12, 'historiaMedica' => 13, 'sexo' => 14, 'idLocalidad' => 15, 'idPais' => 16, 'idChips' => 17, 'updatedAt' => 18, 'updatedBy' => 19, 'createdAt' => 20, 'createdBy' => 21, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::DOCUMENTO => 1, self::ID_TIPO_DOCUMENTO => 2, self::NOMBRE => 3, self::APELLIDO => 4, self::TELEFONO => 5, self::MOVIL => 6, self::TELEFONO_EMERGENCIA => 7, self::DIRECCION => 8, self::FECHA_NACIMIENTO => 9, self::PAREJA => 10, self::HIJOS => 11, self::ID_SOCIEDAD_MEDICA => 12, self::HISTORIA_MEDICA => 13, self::SEXO => 14, self::ID_LOCALIDAD => 15, self::ID_PAIS => 16, self::ID_CHIPS => 17, self::UPDATED_AT => 18, self::UPDATED_BY => 19, self::CREATED_AT => 20, self::CREATED_BY => 21, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'documento' => 1, 'id_tipo_documento' => 2, 'nombre' => 3, 'apellido' => 4, 'telefono' => 5, 'movil' => 6, 'telefono_emergencia' => 7, 'direccion' => 8, 'fecha_nacimiento' => 9, 'pareja' => 10, 'hijos' => 11, 'id_sociedad_medica' => 12, 'historia_medica' => 13, 'sexo' => 14, 'id_localidad' => 15, 'id_pais' => 16, 'id_chips' => 17, 'updated_at' => 18, 'updated_by' => 19, 'created_at' => 20, 'created_by' => 21, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new CorredorMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CorredorPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CorredorPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(CorredorPeer::ID);

		$criteria->addSelectColumn(CorredorPeer::DOCUMENTO);

		$criteria->addSelectColumn(CorredorPeer::ID_TIPO_DOCUMENTO);

		$criteria->addSelectColumn(CorredorPeer::NOMBRE);

		$criteria->addSelectColumn(CorredorPeer::APELLIDO);

		$criteria->addSelectColumn(CorredorPeer::TELEFONO);

		$criteria->addSelectColumn(CorredorPeer::MOVIL);

		$criteria->addSelectColumn(CorredorPeer::TELEFONO_EMERGENCIA);

		$criteria->addSelectColumn(CorredorPeer::DIRECCION);

		$criteria->addSelectColumn(CorredorPeer::FECHA_NACIMIENTO);

		$criteria->addSelectColumn(CorredorPeer::PAREJA);

		$criteria->addSelectColumn(CorredorPeer::HIJOS);

		$criteria->addSelectColumn(CorredorPeer::ID_SOCIEDAD_MEDICA);

		$criteria->addSelectColumn(CorredorPeer::HISTORIA_MEDICA);

		$criteria->addSelectColumn(CorredorPeer::SEXO);

		$criteria->addSelectColumn(CorredorPeer::ID_LOCALIDAD);

		$criteria->addSelectColumn(CorredorPeer::ID_PAIS);

		$criteria->addSelectColumn(CorredorPeer::ID_CHIPS);

		$criteria->addSelectColumn(CorredorPeer::UPDATED_AT);

		$criteria->addSelectColumn(CorredorPeer::UPDATED_BY);

		$criteria->addSelectColumn(CorredorPeer::CREATED_AT);

		$criteria->addSelectColumn(CorredorPeer::CREATED_BY);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Corredor
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CorredorPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CorredorPeer::populateObjects(CorredorPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CorredorPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Corredor $value A Corredor object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Corredor $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Corredor object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Corredor) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Corredor object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Corredor Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CorredorPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CorredorPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CorredorPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related TipoDocumento table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTipoDocumento(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related SociedadMedica table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinSociedadMedica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Localidad table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinLocalidad(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Pais table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPais(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Chip table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinChip(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with their TipoDocumento objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTipoDocumento(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);
		TipoDocumentoPeer::addSelectColumns($c);

		$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = TipoDocumentoPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Corredor) to $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with their SociedadMedica objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinSociedadMedica(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);
		SociedadMedicaPeer::addSelectColumns($c);

		$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = SociedadMedicaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = SociedadMedicaPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					SociedadMedicaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Corredor) to $obj2 (SociedadMedica)
				$obj2->addCorredor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with their Localidad objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinLocalidad(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);
		LocalidadPeer::addSelectColumns($c);

		$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = LocalidadPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = LocalidadPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					LocalidadPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Corredor) to $obj2 (Localidad)
				$obj2->addCorredor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with their Pais objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPais(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);
		PaisPeer::addSelectColumns($c);

		$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PaisPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = PaisPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PaisPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Corredor) to $obj2 (Pais)
				$obj2->addCorredor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with their Chip objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinChip(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);
		ChipPeer::addSelectColumns($c);

		$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ChipPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ChipPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ChipPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Corredor) to $obj2 (Chip)
				$obj2->addCorredor($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CorredorPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
		$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		TipoDocumentoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (TipoDocumentoPeer::NUM_COLUMNS - TipoDocumentoPeer::NUM_LAZY_LOAD_COLUMNS);

		SociedadMedicaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SociedadMedicaPeer::NUM_COLUMNS - SociedadMedicaPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		ChipPeer::addSelectColumns($c);
		$startcol7 = $startcol6 + (ChipPeer::NUM_COLUMNS - ChipPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
		$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
		$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
		$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
		$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined TipoDocumento rows

			$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = TipoDocumentoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);
			} // if joined row not null

			// Add objects for joined SociedadMedica rows

			$key3 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = SociedadMedicaPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = SociedadMedicaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SociedadMedicaPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (SociedadMedica)
				$obj3->addCorredor($obj1);
			} // if joined row not null

			// Add objects for joined Localidad rows

			$key4 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = LocalidadPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LocalidadPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Localidad)
				$obj4->addCorredor($obj1);
			} // if joined row not null

			// Add objects for joined Pais rows

			$key5 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = PaisPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = PaisPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					PaisPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Pais)
				$obj5->addCorredor($obj1);
			} // if joined row not null

			// Add objects for joined Chip rows

			$key6 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol6);
			if ($key6 !== null) {
				$obj6 = ChipPeer::getInstanceFromPool($key6);
				if (!$obj6) {

					$omClass = ChipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj6 = new $cls();
					$obj6->hydrate($row, $startcol6);
					ChipPeer::addInstanceToPool($obj6, $key6);
				} // if obj6 loaded

				// Add the $obj1 (Corredor) to the collection in $obj6 (Chip)
				$obj6->addCorredor($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related TipoDocumento table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTipoDocumento(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related SociedadMedica table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptSociedadMedica(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Localidad table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptLocalidad(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Pais table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPais(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Chip table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptChip(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CorredorPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$criteria->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseCorredorPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects except TipoDocumento.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTipoDocumento(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		SociedadMedicaPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (SociedadMedicaPeer::NUM_COLUMNS - SociedadMedicaPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		ChipPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (ChipPeer::NUM_COLUMNS - ChipPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined SociedadMedica rows

				$key2 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = SociedadMedicaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = SociedadMedicaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					SociedadMedicaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (SociedadMedica)
				$obj2->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Localidad rows

				$key3 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = LocalidadPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					LocalidadPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (Localidad)
				$obj3->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key4 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PaisPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PaisPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PaisPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Pais)
				$obj4->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Chip rows

				$key5 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = ChipPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = ChipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					ChipPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Chip)
				$obj5->addCorredor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects except SociedadMedica.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptSociedadMedica(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		TipoDocumentoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (TipoDocumentoPeer::NUM_COLUMNS - TipoDocumentoPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		ChipPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (ChipPeer::NUM_COLUMNS - ChipPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined TipoDocumento rows

				$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = TipoDocumentoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Localidad rows

				$key3 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = LocalidadPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					LocalidadPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (Localidad)
				$obj3->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key4 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PaisPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PaisPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PaisPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Pais)
				$obj4->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Chip rows

				$key5 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = ChipPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = ChipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					ChipPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Chip)
				$obj5->addCorredor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects except Localidad.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptLocalidad(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		TipoDocumentoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (TipoDocumentoPeer::NUM_COLUMNS - TipoDocumentoPeer::NUM_LAZY_LOAD_COLUMNS);

		SociedadMedicaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SociedadMedicaPeer::NUM_COLUMNS - SociedadMedicaPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		ChipPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (ChipPeer::NUM_COLUMNS - ChipPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined TipoDocumento rows

				$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = TipoDocumentoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined SociedadMedica rows

				$key3 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = SociedadMedicaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = SociedadMedicaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SociedadMedicaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (SociedadMedica)
				$obj3->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key4 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PaisPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PaisPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PaisPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Pais)
				$obj4->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Chip rows

				$key5 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = ChipPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = ChipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					ChipPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Chip)
				$obj5->addCorredor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects except Pais.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPais(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		TipoDocumentoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (TipoDocumentoPeer::NUM_COLUMNS - TipoDocumentoPeer::NUM_LAZY_LOAD_COLUMNS);

		SociedadMedicaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SociedadMedicaPeer::NUM_COLUMNS - SociedadMedicaPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		ChipPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (ChipPeer::NUM_COLUMNS - ChipPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_CHIPS,), array(ChipPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined TipoDocumento rows

				$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = TipoDocumentoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined SociedadMedica rows

				$key3 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = SociedadMedicaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = SociedadMedicaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SociedadMedicaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (SociedadMedica)
				$obj3->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Localidad rows

				$key4 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = LocalidadPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LocalidadPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Localidad)
				$obj4->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Chip rows

				$key5 = ChipPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = ChipPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = ChipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					ChipPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Chip)
				$obj5->addCorredor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Corredor objects pre-filled with all related objects except Chip.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Corredor objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptChip(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		CorredorPeer::addSelectColumns($c);
		$startcol2 = (CorredorPeer::NUM_COLUMNS - CorredorPeer::NUM_LAZY_LOAD_COLUMNS);

		TipoDocumentoPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (TipoDocumentoPeer::NUM_COLUMNS - TipoDocumentoPeer::NUM_LAZY_LOAD_COLUMNS);

		SociedadMedicaPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (SociedadMedicaPeer::NUM_COLUMNS - SociedadMedicaPeer::NUM_LAZY_LOAD_COLUMNS);

		LocalidadPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (LocalidadPeer::NUM_COLUMNS - LocalidadPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(CorredorPeer::ID_TIPO_DOCUMENTO,), array(TipoDocumentoPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_SOCIEDAD_MEDICA,), array(SociedadMedicaPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_LOCALIDAD,), array(LocalidadPeer::ID,), $join_behavior);
				$c->addJoin(array(CorredorPeer::ID_PAIS,), array(PaisPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = CorredorPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = CorredorPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = CorredorPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				CorredorPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined TipoDocumento rows

				$key2 = TipoDocumentoPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = TipoDocumentoPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = TipoDocumentoPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					TipoDocumentoPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj2 (TipoDocumento)
				$obj2->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined SociedadMedica rows

				$key3 = SociedadMedicaPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = SociedadMedicaPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = SociedadMedicaPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					SociedadMedicaPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj3 (SociedadMedica)
				$obj3->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Localidad rows

				$key4 = LocalidadPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = LocalidadPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = LocalidadPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LocalidadPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj4 (Localidad)
				$obj4->addCorredor($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key5 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = PaisPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = PaisPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					PaisPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Corredor) to the collection in $obj5 (Pais)
				$obj5->addCorredor($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return CorredorPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Corredor or Criteria object.
	 *
	 * @param      mixed $values Criteria or Corredor object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCorredorPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Corredor object
		}

		if ($criteria->containsKey(CorredorPeer::ID) && $criteria->keyContainsValue(CorredorPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CorredorPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseCorredorPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Corredor or Criteria object.
	 *
	 * @param      mixed $values Criteria or Corredor object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCorredorPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCorredorPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CorredorPeer::ID);
			$selectCriteria->add(CorredorPeer::ID, $criteria->remove(CorredorPeer::ID), $comparison);

		} else { // $values is Corredor object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseCorredorPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseCorredorPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the corredor table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CorredorPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Corredor or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Corredor object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CorredorPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Corredor) {
			// invalidate the cache for this single object
			CorredorPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CorredorPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				CorredorPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Corredor object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Corredor $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Corredor $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CorredorPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CorredorPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(CorredorPeer::DATABASE_NAME, CorredorPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = CorredorPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Corredor
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CorredorPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CorredorPeer::DATABASE_NAME);
		$criteria->add(CorredorPeer::ID, $pk);

		$v = CorredorPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CorredorPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CorredorPeer::DATABASE_NAME);
			$criteria->add(CorredorPeer::ID, $pks, Criteria::IN);
			$objs = CorredorPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseCorredorPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the CorredorPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the CorredorPeer class:
//
// Propel::getDatabaseMap(CorredorPeer::DATABASE_NAME)->addTableBuilder(CorredorPeer::TABLE_NAME, CorredorPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseCorredorPeer::DATABASE_NAME)->addTableBuilder(BaseCorredorPeer::TABLE_NAME, BaseCorredorPeer::getMapBuilder());

