<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2008/10/09 22:19:16
sfConfig::set('sf_compat_10', true);
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoUsuarios/actions/actions.class.php');

